services:
  - type: web
    name: hotel-management
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-management-db
          property: connectionString
    database:
      name: hotel-management-db
      plan: free
